package com.qvision.metlife.pages;

import org.junit.Assert;
import org.openqa.selenium.WebElement;

import com.qvision.metlife.utils.Helpers;

import net.serenitybdd.core.annotations.findby.FindBy;
import net.serenitybdd.core.pages.PageObject;
import net.thucydides.core.annotations.DefaultUrl;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@DefaultUrl("https://qa.salespilot.metlife.com.co/")
public class LoginMetLifePages extends PageObject {
	
	Helpers help = new Helpers();

	@FindBy(name = "USER")
	WebElement txtUser;

	@FindBy(name = "PASSWORD")
	WebElement txtPasswd;

	@FindBy(id = "btnSubmit")
	WebElement btnIngresar;

	@FindBy(id = "dashboardTab")
	WebElement lblValditeAccess;

	public void formLogin(String user, String passwd) {

		txtUser.sendKeys(user);
		txtPasswd.sendKeys(passwd);

	}

	public void validateAccess() {

		btnIngresar.click();
		help.wait(2000);
		Assert.assertEquals("Menú Principal", lblValditeAccess.getText());
	}

}
