package com.qvision.metlife.runners;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.SnippetType;
import net.serenitybdd.cucumber.CucumberWithSerenity;


@RunWith(CucumberWithSerenity.class)
@CucumberOptions(

		features = "src/test/resources/com/qvision/metlife/features/LoginGsp.feature", glue = "com.qvision.metlife.stepsdefinitions", snippets = SnippetType.CAMELCASE)

public class LoginMetLifeRunner {

}
